### ISSUE TITLE
menufindFood2

### ISSUE THREAD

**Issue by takeshou** [yuki-shinno/FoodCompositionJapan#1]
中澤先生のmenufindFood()関数を見て、最初からキーワードを使えるようにしてみました。
何も指定しなければ、中澤先生のmenufindFood()関数と同じ動作をします。

menufindFood2 = function(keys = NULL) {
  grp = getFoodGroups()[menu(getFoodGroups(), graphics = TRUE)]
  if(is.null(keys)){
    res1 = findFood(keyword = readline(), food_group = grp)
  }else{
    res1 = findFood(keys, food_group = grp)
  }
  res1[menu(res1[, "food_and_description"], graphics = TRUE), ]
}

プルリクというほどでもないし、ホントはブログのコメントにと思いましたが、コメント欄がなかったので、こちらに。

**Comment by yuki-shinno** [comment]
ありがとうございます！今さらながら気づきました。
機能を盛りこませていただきました。
